version: '3'
services:
  backend:
    build:
      context: ./websocket-trade
    ports:
      - "8080:8080"
    volumes:
      - ./websocket-trade:/usr/src/app
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
